#!/usr/bin/env bash
# agent-pipeline Bootstrap: erzeugt Dispatcher-Stubs im Konsumenten-Repo.
#
# Aufruf (aus der Wurzel des KONSUMENTEN-Repos):
#   gh api repos/deleonio/agent-pipeline/contents/init.sh -H "Accept: application/vnd.github.raw" > init.sh
#   bash init.sh [--tag v1.0] [--repo owner/repo] [--dry-run]
#
# Idempotent: Stubs mit Generator-Marker werden überschrieben (Re-Pin auf neuen
# Minor-Tag = erneuter Lauf mit --tag v1.x). NICHT generierte Dateien mit gleichem
# Namen brechen den Lauf ab — Schutz vor dem Überschreiben einer Alt-Installation.
#
# Labels muss init.sh NICHT anlegen: die Phasen-Workflows erstellen sie idempotent
# selbst (gh label create … || true).
set -euo pipefail

PIPELINE_REPO="deleonio/agent-pipeline"
TAG="v1.0"
DRY_RUN=false
REPO=""

while [ $# -gt 0 ]; do
  case "$1" in
    --tag) TAG="${2:?--tag braucht einen Wert}"; shift 2 ;;
    --dry-run) DRY_RUN=true; shift ;;
    --repo) REPO="${2:?--repo braucht einen Wert}"; shift 2 ;;
    *) echo "Unbekannte Option: $1" >&2; exit 2 ;;
  esac
done

command -v gh >/dev/null 2>&1 || { echo "✗ gh CLI fehlt."; exit 1; }
[ -n "$REPO" ] || REPO="$(gh repo view --json nameWithOwner --jq .nameWithOwner)"
echo "▸ Konsumenten-Repo: $REPO — Pin: $PIPELINE_REPO@$TAG"

# ── 1) Stubs schreiben ────────────────────────────────────────────────────────
# Dateinamen sind VERTRAG (gate-merge-Allowlist, Sweep-Dispatch, pr-cancel) —
# exakt diese neun, nicht umbenennen.
STUBS=(
  01-claude-triage.yml
  02-claude-ux.yml
  03-claude-spec.yml
  04-claude-implement.yml
  05-claude-pr-review.yml
  06-claude-pr-fixup.yml
  06b-documenter-sweep.yml
  07-claude-pr-documenter.yml
  claude-pr-gate-merge.yml
)

write_stub() {
  local src="$1" dest=".github/workflows/$1"
  if [ -f "$dest" ] && ! grep -q "generated by agent-pipeline@" "$dest"; then
    echo "✗ $dest existiert und ist NICHT von agent-pipeline generiert — abgebrochen (nichts überschrieben)." >&2
    exit 1
  fi
  local content
  content="$(gh api "repos/$PIPELINE_REPO/contents/stubs/$src?ref=$TAG" \
    -H "Accept: application/vnd.github.raw")"
  # Pin im Stub auf den angeforderten Tag umbiegen (im Repo liegen die Templates
  # mit dem jeweiligen Release-Tag gepinnt; Re-Pin = Re-Run mit anderem --tag).
  if [ "$DRY_RUN" = true ]; then
    echo "  [dry-run] würde $dest schreiben ($TAG)"
  else
    printf '%s\n' "$content" \
      | sed -E "s#(@${PIPELINE_REPO}/[^@]+@)v[0-9]+\.[0-9]+#\1${TAG}#g; s#(generated by agent-pipeline@)v[0-9]+\.[0-9]+#\1${TAG}#g" \
      > "$dest"
    echo "  ✓ $dest ($TAG)"
  fi
}

mkdir -p .github/workflows
for s in "${STUBS[@]}"; do
  write_stub "$s"
done

# ── 2) Minimale .claude/settings.json (nur falls fehlt) ──────────────────────
# Der Memory-Mechanismus setzt autoMemoryDirectory voraus. Bestehende Dateien
# (z. B. mit enabledMcpjsonServers) bleiben unangetastet.
if [ ! -f .claude/settings.json ]; then
  if [ "$DRY_RUN" = true ]; then
    echo "  [dry-run] würde minimale .claude/settings.json schreiben"
  else
    mkdir -p .claude
    printf '{\n  "autoMemoryDirectory": ".claude/memory"\n}\n' > .claude/settings.json
    echo "  ✓ .claude/settings.json (minimal, autoMemoryDirectory)"
  fi
fi

# ── 3) Secrets / Vars / Access prüfen (warnen, nicht blockieren) ─────────────
echo "▸ Konfigurations-Check"
secrets="$(gh secret list -R "$REPO" --json name --jq '.[].name' 2>/dev/null | sort || true)"
for s in APP_ID APP_PRIVATE_KEY; do
  grep -qx "$s" <<<"$secrets" \
    || echo "  ⚠ Secret $s fehlt — Pipeline ist App-only (ohne App-Token: kein Push, keine Folge-Trigger)."
done

provider="$(gh variable list -R "$REPO" --json name,value \
  --jq '.[] | select(.name == "LLM_PROVIDER") | .value' 2>/dev/null || true)"
provider="${provider:-claude}"
case "$provider" in
  zai)        need_key=ZAI_API_KEY ;;
  openrouter) need_key=OPENROUTER_API_KEY ;;
  claude)     need_key=CLAUDE_API_KEY ;;
  *) echo "  ⚠ vars.LLM_PROVIDER='$provider' ist unbekannt (erlaubt: claude|zai|openrouter)."; need_key="" ;;
esac
[ -z "$need_key" ] || grep -qx "$need_key" <<<"$secrets" \
  || echo "  ⚠ Secret $need_key fehlt (vars.LLM_PROVIDER=$provider)."

access="$(gh api "repos/$PIPELINE_REPO/actions/permissions/access" \
  --jq .access_level 2>/dev/null || echo '?')"
[ "$access" = "user" ] \
  || echo "  ⚠ Access-Level des Pipeline-Repos ist '${access}' (erwartet 'user') — Pipeline-Repo: Settings → Actions → General → Access → „Accessible from repositories in the account“."

echo "▸ Erinnerung: GitHub App muss auf $REPO installiert sein (Contents/Issues/PR/Actions: Read+Write,installation)"
echo "  UND auf $PIPELINE_REPO (lesend genügt — für den .agent-pipeline-Checkout per App-Token)."
echo
echo "Fertig. Stubs committen, Secrets/App prüfen — Labels legt die Pipeline selbst an."
